/** @format */

export const actionsTypes = {
  CHANGE_SEARCH_WORD_AND_ARRAY_TIPS: "CHANGE_SEARCH_WORD_AND_ARRAY_TIPS",
  GET_PHOTOS_FROM_API: "GET_PHOTOS_FROM_API",
  CHANGE_KEYWORD_FROM_THE_TIPS_LIST: "CHANGE_KEYWORD_FROM_THE_TIPS_LIST",
  CHANGE_INPUT: "CHANGE_INPUT",
};
